apiVersion: v1
kind: Secret
metadata:
  name: dapr-sandbox-device-telemetry-secrets
  labels:
    app: dapr-sandbox
    component: actors
    area: app-runtime
data:
  functionStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWRhcHJhY3RvcnM7QWNjb3VudEtleT1sclBydkEzZm5rdSt6VWRvandlYWF3NDFodVJxLzUxUXJGQm40L0N4RDFMYmFOaHF6THRqWHMxM0ZFblMyeGY0NDJYV0puc2VjQ1hQMTBFV0ZOY1E2dz09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  eventHubsConnectionstring: RW5kcG9pbnQ9c2I6Ly9kYXByLWFjdG9ycy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPU1hbmFnZTtTaGFyZWRBY2Nlc3NLZXk9R1Yzb1BvZGk4c2xRbHQxdDNGaTdVV2FQcFVDV3RxR29QL0U3dUs2cG9hbz07RW50aXR5UGF0aD1kZXZpY2UtbWVzc2FnZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-telemetry-stream-processor
  labels:
    app: dapr-sandbox
    component: device-telemetry
    area: app-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-sandbox
      component: device-telemetry
      area: app-runtime
  template:
    metadata:
      labels:
        app: dapr-sandbox
        component: device-telemetry
        area: app-runtime
    spec:
      containers:
      - name: device-telemetry
        image: tomkerkhove/dapr-sandbox-streaming-device-telemetry:dev
        ports:
        # Port for HTTP triggered functions
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: device-message-processor
        - name: DeviceRegistry.API.BaseUri
          value: "http://dapr-sandbox-apis-device-service"
        - name: AzureWebJobsStorage
          valueFrom:
            secretKeyRef:
              name: dapr-sandbox-device-telemetry-secrets
              key: functionStorage
        - name: EventHubs.ConnectionStrings.DeviceMessages
          valueFrom:
            secretKeyRef:
              name: dapr-sandbox-device-telemetry-secrets
              key: eventHubsConnectionstring
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: device-telemetry-autoscale
  labels:
    app: dapr-sandbox
    component: device-telemetry
    area: autoscaling
spec:
  scaleTargetRef:
    deploymentName: device-telemetry-stream-processor
  triggers:
  - type: azure-eventhub
    metadata:
      connection: EventHubs.ConnectionStrings.DeviceMessages
      storageConnection: AzureWebJobsStorage
      blobContainer: azure-webjobs-eventhub