apiVersion: v1
kind: Secret
metadata:
  name: dapr-sandbox-actors-secrets
  labels:
    app: dapr-sandbox
    component: actors
    area: app-runtime
data:
  applicationInsightsKey: NjQyZGM1MTYtZWY5Zi00NzVmLTkzMzAtMWMxN2E3MTM2NTFi
  # This is a hack because it should come from Azure Key Vault, just like all secrets actually
  demoDeviceConnectionString: SG9zdE5hbWU9ZGFwci1hY3RvcnMuYXp1cmUtZGV2aWNlcy5uZXQ7RGV2aWNlSWQ9ZGVtby1kZXZpY2U7U2hhcmVkQWNjZXNzS2V5PXNWalBoWStBYkRpczNzZHZNdVBJT1BxQkVhVlM3WmFEOFBGMVR2RmhObEE9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-sandbox-actors
  labels:
    app: dapr-sandbox
    component: actors
    area: app-runtime
spec:
  selector:
    matchLabels:
      app: dapr-sandbox
      component: actors
      area: app-runtime
  template:
    metadata:
      labels:
        app: dapr-sandbox
        component: actors
        area: app-runtime
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "actors-runtime"
        dapr.io/port: "3000"
    spec:
      containers:
      - name: actor-runtime
        image: tomkerkhove/dapr-sandbox-iot-actors:dev
        env:
        - name: APPLICATION_INSIGHTS
          valueFrom:
            secretKeyRef:
              name: dapr-sandbox-actors-secrets
              key: applicationInsightsKey
        - name: IOTHUB_CONNECTIONSTRING_DEVICE_demo-device
          valueFrom:
            secretKeyRef:
              name: dapr-sandbox-actors-secrets
              key: demoDeviceConnectionString